"""Final initial migration

Revision ID: a53cf660ed28
Revises: 
Create Date: 2025-08-21 00:10:26.078319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53cf660ed28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mailing_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mailing_list_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_mailing_list_status'), ['status'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(length=100), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('created_for_email', sa.String(length=150), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_url_created_for_email'), ['created_for_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_url_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_short_url_long_url'), ['long_url'], unique=False, mysql_length=255)
        batch_op.create_index(batch_op.f('ix_short_url_short_code'), ['short_code'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('click_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['short_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_log_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_url_id'), ['url_id'], unique=False)
        batch_op.create_index('ix_click_log_url_id_timestamp', ['url_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_utm_campaign'), ['utm_campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_utm_source'), ['utm_source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_log_utm_source'))
        batch_op.drop_index(batch_op.f('ix_click_log_utm_campaign'))
        batch_op.drop_index('ix_click_log_url_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_click_log_url_id'))
        batch_op.drop_index(batch_op.f('ix_click_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_click_log_device_type'))
        batch_op.drop_index(batch_op.f('ix_click_log_country'))

    op.drop_table('click_log')
    op.drop_table('user')
    with op.batch_alter_table('short_url', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_url_short_code'))
        batch_op.drop_index(batch_op.f('ix_short_url_long_url'))
        batch_op.drop_index(batch_op.f('ix_short_url_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_short_url_created_for_email'))

    op.drop_table('short_url')
    op.drop_table('settings')
    op.drop_table('product')
    with op.batch_alter_table('mailing_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mailing_list_status'))
        batch_op.drop_index(batch_op.f('ix_mailing_list_email'))

    op.drop_table('mailing_list')
    # ### end Alembic commands ###
